version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html:ro
